apiVersion: v1
data:
  dbname: {{ .Values.postgresql.global.postgresql.auth.database | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
  user: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  username: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  host: {{ .Release.Name | printf "%s-postgresql" | b64enc }}
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-cluster-app
type: kubernetes.io/basic-auth