name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    paths: 
      - 'docker/**'
    branches: [ "workflow" ]
    # Publish semver tags as releases.
  pull_request:
    branches: [ "workflow" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          load: true
          tags: ${{ env.IMAGE_NAME }}:test 

  get-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run container and get version
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:test /bin/sh -c "
            VERSION=$(/algorand/node/algod -v | head -n 2 | tail -n -1 | cut -d ' ' -f 1);
            echo \"Version: $VERSION\""